# Generated by Django 4.1.10 on 2024-08-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_unique_id', models.CharField(max_length=255, unique=True)),
                ('check_id', models.CharField(max_length=255)),
                ('check_title', models.TextField()),
                ('check_type', models.JSONField()),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('status_extended', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_details', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk', models.TextField(blank=True, null=True)),
                ('related_url', models.URLField(blank=True, null=True)),
                ('remediation', models.JSONField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('depends_on', models.JSONField(blank=True, null=True)),
                ('related_to', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('account_id', models.CharField(max_length=50)),
                ('organizations_info', models.JSONField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_tags', models.JSONField(blank=True, null=True)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'GCP'), ('azure', 'AZURE')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('config_details', models.JSONField()),
                ('compliances', models.ManyToManyField(blank=True, related_name='scan_configurations', to='monitoring_app.compliance')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.cloudprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scan_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='monitoring_app.scanconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ProwlerCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring_app.cloudprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('checks', models.ManyToManyField(related_name='compliance_controls', to='monitoring_app.prowlercheck')),
                ('compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='monitoring_app.compliance')),
            ],
        ),
        migrations.CreateModel(
            name='CheckControlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('check_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.check')),
                ('compliance_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.compliancecontrol')),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='compliances',
            field=models.ManyToManyField(through='monitoring_app.CheckControlMapping', to='monitoring_app.compliancecontrol'),
        ),
        migrations.AddField(
            model_name='check',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring_app.scan'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['start_time'], name='monitoring__start_t_d7fbff_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['status'], name='monitoring__status_ad03b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkcontrolmapping',
            unique_together={('check_instance', 'compliance_control')},
        ),
        migrations.AddIndex(
            model_name='check',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
    ]
